# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: App SDKs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build-OpenAPI-Spec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./host-functions-api/src
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./host-functions-api/src

      - run: npm ci
      - run: npm run tsp:compile

      - name: Archive OpenAPI Spec File
        uses: actions/upload-artifact@v4
        with:
          name: sdk.yaml
          path: ./host-functions-api/src/tsp-output/sdk.yaml

  Build-TypeScript-SDK:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./host-functions-api/src # needed so that the cache folder is correctly identified
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./host-functions-api/src

      - name: Download OpenAPI Spec
        uses: actions/download-artifact@v4
        with:
          name: sdk.yaml
          path: ./host-functions-api/src/tsp-output/

      - run: npm ci
      - run: npm run sdk:compile-typescript

      - name: Archive TypeScript SDK
        uses: actions/upload-artifact@v4
        with:
          name: ubiq-sdk-typescript
          path: ./sdk-output/ubiq-sdk-typescript/
    needs: Build-OpenAPI-Spec
